
export const REASSIGN_MOCK_EXTRACTION_RESPONSE = 
{
  "batch_id": "faed514c2d5e4ee788bd7ae2b3ea9e23",
  "hbl_groups": [
    {
      "group_id": "hbl-group-1",
      "document_ids": [
        "document-1"
      ],
      "same_shipper_and_consignee": false,
      "hbl_action": "create_separate_hbl",
      "reason": "This document has different or incomplete shipper/consignee details.",
      "combined_extraction": {
        "packing_list_number": null,
        "packing_list_date": null,
        "invoice_number": "1009155084",
        "invoice_date": "07.08.2026",
        "exporter_reference": null,
        "ie_code": null,
        "branch_code": null,
        "buyer_order_number": null,
        "buyer_order_date": null,
        "other_references": [],
        "shipper_exporter": {
          "name": "Southern Engineering Works Pvt. Ltd.",
          "address": "No. 72, Industrial Estate Ambattur Chennai, Tamil Nadu 600058 India",
          "tax_id": null
        },
        "consignee": {
          "name": "NordWest Industrial Logistics GmbH",
          "address": "Waltershofer Strasse 18 21107 Hamburg Germany",
          "tax_id": null
        },
        "buyer": {
          "name": "RheinTech Anlagenbau AG",
          "address": "Robert-Bosch-Strasse 11 73776 Altbach Germany",
          "tax_id": null
        },
        "notify_party": null,
        "country_of_origin": "INDIA",
        "country_of_final_destination": "GERMANY",
        "pre_carriage_by": "SEA",
        "place_of_receipt": "AVITO LOGISTICS",
        "vessel_name": null,
        "voyage_or_flight_number": null,
        "port_of_loading": "ENNORE",
        "route_or_place_of_transshipment": null,
        "port_of_discharge": "HAMBURG",
        "place_of_final_delivery": "ALTBACH SITE",
        "type_of_movement": null,
        "incoterms": "DAP/DELIVERY AT PLACE",
        "payment_terms": "NETT 60 DYS FRM D OF RCT AT CU",
        "freight_terms": null,
        "freight_amount": null,
        "release_terms": null,
        "shipment_reference": null,
        "place_of_issue": null,
        "date_of_issue": null,
        "shipped_on_board_date": null,
        "number_of_originals": null,
        "delivery_contact": null,
        "other_particulars": null,
        "marks_and_numbers": null,
        "total_package_count": "54 CRATES",
        "total_package_type": null,
        "total_gross_weight": "21296 KG",
        "total_net_weight": "19514.88 KG",
        "total_measurement": null,
        "items": [
          {
            "product_code": "6904051-0000",
            "item_product_description": "1124,480,042 OUTPUT GEAR",
            "package_numbers": "Crate nos C581-C596",
            "index_number": null,
            "hsn_code": "87084000",
            "quantity": "26880",
            "unit_of_measure": "PC'S",
            "package_count": null,
            "package_type": null,
            "gross_weight": null,
            "net_weight": "7929.60",
            "dimensions": null,
            "cbm_volume": null,
            "container_number": null,
            "seal_number": null,
            "shipping_marks": null
          },
          {
            "product_code": "6904041-0000",
            "item_product_description": "1124480043-INPUT GEAR",
            "package_numbers": "Crate nos C1035-C1074",
            "index_number": null,
            "hsn_code": "87084000",
            "quantity": "26880",
            "unit_of_measure": "PC'S",
            "package_count": null,
            "package_type": null,
            "gross_weight": null,
            "net_weight": "11585.28",
            "dimensions": null,
            "cbm_volume": null,
            "container_number": null,
            "seal_number": null,
            "shipping_marks": null
          }
        ],
        "containers": []
      }
    },
    {
      "group_id": "hbl-group-2",
      "document_ids": [
        "document-3",
        "document-2"
      ],
      "same_shipper_and_consignee": true,
      "hbl_action": "create_combined_hbl",
      "reason": "Documents were manually combined into this HBL group.",
      "combined_extraction": {
        "packing_list_number": null,
        "packing_list_date": null,
        "invoice_number": "1009155078",
        "invoice_date": "2026-07-30",
        "exporter_reference": null,
        "ie_code": null,
        "branch_code": null,
        "buyer_order_number": null,
        "buyer_order_date": null,
        "other_references": [],
        "shipper_exporter": {
          "name": "Southern Engineering Works Pvt. Ltd.",
          "address": "No. 18, SIPCOT Industrial Complex Gummidipoondi Tamil Nadu 601201 India",
          "tax_id": null
        },
        "consignee": {
          "name": "NordWest Industrial Logistics GmbH",
          "address": "Köhlbranddeich 22 20457 Hamburg Germany",
          "tax_id": null
        },
        "buyer": {
          "name": null,
          "address": "Dieselstrasse 14 73776 Altbach Germany",
          "tax_id": null
        },
        "notify_party": null,
        "country_of_origin": "INDIA",
        "country_of_final_destination": "GERMANY",
        "pre_carriage_by": "SEA",
        "place_of_receipt": "AVITO, LOGISTICS",
        "vessel_name": null,
        "voyage_or_flight_number": null,
        "port_of_loading": "ENNORE",
        "route_or_place_of_transshipment": null,
        "port_of_discharge": "HAMBURG",
        "place_of_final_delivery": "ALTBACH SITE",
        "type_of_movement": null,
        "incoterms": "DAP/DELIVERY AT PLACE",
        "payment_terms": "NETT 60 DYS FRM D OF RCT AT CU",
        "freight_terms": null,
        "freight_amount": null,
        "release_terms": null,
        "shipment_reference": null,
        "place_of_issue": null,
        "date_of_issue": null,
        "shipped_on_board_date": null,
        "number_of_originals": null,
        "delivery_contact": null,
        "other_particulars": null,
        "marks_and_numbers": null,
        "total_package_count": "94 CRATES",
        "total_package_type": null,
        "total_gross_weight": "43465 KG",
        "total_net_weight": "38387.42 KG",
        "total_measurement": null,
        "items": [
          {
            "product_code": "6904010-0000",
            "item_product_description": "1122480014 PLANET GEAR",
            "package_numbers": "Crate nos C146-C149",
            "index_number": "b",
            "hsn_code": "87084000",
            "quantity": "25344",
            "unit_of_measure": "PC'S",
            "package_count": null,
            "package_type": null,
            "gross_weight": null,
            "net_weight": "2686.46",
            "dimensions": null,
            "cbm_volume": null,
            "container_number": null,
            "seal_number": null,
            "shipping_marks": null
          },
          {
            "product_code": "6904051-0000",
            "item_product_description": "1124.480.042 OUTPUT GEAR",
            "package_numbers": "Crate nos C556-C557",
            "index_number": null,
            "hsn_code": "87084000",
            "quantity": "20160",
            "unit_of_measure": "PC'S",
            "package_count": null,
            "package_type": null,
            "gross_weight": null,
            "net_weight": "5947.20",
            "dimensions": null,
            "cbm_volume": null,
            "container_number": null,
            "seal_number": null,
            "shipping_marks": null
          },
          {
            "product_code": "6904021-0000",
            "item_product_description": "1116480057-INPUT GEAR",
            "package_numbers": "Crate nos C197 - C202",
            "index_number": null,
            "hsn_code": "87084000",
            "quantity": "4032",
            "unit_of_measure": "PC'S",
            "package_count": null,
            "package_type": null,
            "gross_weight": null,
            "net_weight": "1612.80",
            "dimensions": null,
            "cbm_volume": null,
            "container_number": null,
            "seal_number": null,
            "shipping_marks": null
          },
          {
            "product_code": "6904041-0000",
            "item_product_description": "1124480043-INPUT GEAR",
            "package_numbers": "Crate nos C7-C24",
            "index_number": "A",
            "hsn_code": "87084000",
            "quantity": "19440",
            "unit_of_measure": "PC'S",
            "package_count": null,
            "package_type": null,
            "gross_weight": null,
            "net_weight": "8378.64",
            "dimensions": null,
            "cbm_volume": null,
            "container_number": null,
            "seal_number": null,
            "shipping_marks": null
          },
          {
            "product_code": "6904010-0000",
            "item_product_description": "1122480014 PLANET GEAR",
            "package_numbers": "C150-C153",
            "index_number": "b",
            "hsn_code": "87084000",
            "quantity": "25344",
            "unit_of_measure": "PC'S",
            "package_count": null,
            "package_type": null,
            "gross_weight": null,
            "net_weight": "2686.46",
            "dimensions": null,
            "cbm_volume": null,
            "container_number": null,
            "seal_number": null,
            "shipping_marks": null
          },
          {
            "product_code": "6904051-0000",
            "item_product_description": "1124.480.042 OUTPUT GEAR",
            "package_numbers": "C568-C581",
            "index_number": null,
            "hsn_code": "87084000",
            "quantity": "21840",
            "unit_of_measure": "PC'S",
            "package_count": null,
            "package_type": null,
            "gross_weight": null,
            "net_weight": "6442.80",
            "dimensions": null,
            "cbm_volume": null,
            "container_number": null,
            "seal_number": null,
            "shipping_marks": null
          },
          {
            "product_code": "6904021-0000",
            "item_product_description": "1116480057-INPUT GEAR",
            "package_numbers": "C203 - C206",
            "index_number": null,
            "hsn_code": "87084000",
            "quantity": "2688",
            "unit_of_measure": "PC'S",
            "package_count": null,
            "package_type": null,
            "gross_weight": null,
            "net_weight": "1075.20",
            "dimensions": null,
            "cbm_volume": null,
            "container_number": null,
            "seal_number": null,
            "shipping_marks": null
          },
          {
            "product_code": "6904041-0000",
            "item_product_description": "1124480043-INPUT GEAR",
            "package_numbers": "C1002-C1034",
            "index_number": "A",
            "hsn_code": "87084000",
            "quantity": "22176",
            "unit_of_measure": "PC'S",
            "package_count": null,
            "package_type": null,
            "gross_weight": null,
            "net_weight": "9557.86",
            "dimensions": null,
            "cbm_volume": null,
            "container_number": null,
            "seal_number": null,
            "shipping_marks": null
          }
        ],
        "containers": []
      }
    }
  ]
}